### PR TITLE
[2.0.0] Improved Types.

### PR DESCRIPTION
**Pull request by tripodsgames**
Implement better types.

Current types(Generic function args):
image

New Types(Typed function args):
image

### CODE REVIEW

**Comment by vlio20** [comment]
@tripodsgames same thing. Unable to merge: https://prnt.sc/20xld7i

**Comment by tripodsgames** [comment]
> @tripodsgames same thing. Unable to merge: https://prnt.sc/20xld7i

I think you will need to use the git cli to merge.

**Comment by vlio20** [comment]
@tripodsgames can you please check version 2.0.0-rc1 to validate that it works with no issues? checked in projects and it looks fine

**Comment by tripodsgames** [comment]
I Will check It later

**Comment by tripodsgames** [comment]
> @tripodsgames can you please check version 2.0.0-rc1 to validate that it works with no issues? checked in projects and it looks fine

It is working as intended!
:smile:

**Comment by vlio20** [comment]
version 2.0.0 is available now. Thanks @tripodsgames !!

**Pull request merged**
